### ISSUE TITLE
Json use case difficult

### ISSUE THREAD

**Issue by janat08** [vmx/jslens#5]
I take it doing json with basic lense is suppose to be trivial enough that this library isnt worth it? I'm trying to standardize json schemas to a common variant, and felt like bidirectionality would be useful.

**Comment by vmx** [comment]
Yes, getting it working with JSON would be quite a bit of work.

**Comment by janat08** [comment]
Does it have to rely on regex?

**Comment by vmx** [comment]
> Does it have to rely on regex?

I would say yes, as it directly operates on the text. So it would even JSON just as text and not as some kind of tree structure.
